# Generated by Django 2.2.13 on 2021-07-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20210730_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
