# Generated by Django 2.2.13 on 2021-07-31 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_auto_20210730_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post'),
            preserve_default=False,
        ),
    ]
