# Generated by Django 2.2.13 on 2021-07-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0014_auto_20210730_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='img',
        ),
    ]
